site_name: Notejam Platform Docs
theme:
  name: material
  features:
    - navigation.tabs
    - search.highlight

nav:
  - Overview: index.md
  - Architecture:
      - High-level: diagrams/architecture.md
      - Network & Security: diagrams/network.md
  - CI / CD: guides/ci-cd.md
  - Infrastructure:
      - Modules & Variables: guides/infra-modules.md
      - Destroy-/ Tear-down: guides/destroy.md
  - Application:
      - Django settings: guides/app-config.md
      - Static assets S3 + CloudFront: guides/static-assets.md
  - ADRs:
      - ADR-001 Bootstrap (Infra Layout): guides/adr-001-bootstrap.md